[package]
name = "bevy_dioxus"
version = "0.0.1"
authors = ["Junichi Sugiura"]
edition = "2021"
description = "Write Cross-platform application with React-like decralative UI framework and scalable ECS architecture all in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/JunichiSugiura/bevy_dioxus/"
homepage = "https://github.com/JunichiSugiura/bevy_dioxus/"
documentation = "https://docs.rs/bevy_dioxus/latest/bevy_dioxus/"
keywords = ["declarative-ui", "ecs", "bevy", "dioxus", "react", "cross-platform", "framework", "desktop", "macOS", "linux", "windows"]
rust-version = "1.56.0"

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy_dioxus_desktop = { path = "./packages/desktop", optional = true }

[dev-dependencies]
leafwing-input-manager = { version = "0.3", default-features = false }
dioxus = "0.2"

[features]
default = ["desktop"]
desktop = ["bevy_dioxus_desktop"]

[workspace]
members = [
    "packages/desktop",
]
