[package]
name = "bevy_dioxus_desktop"
version = "0.0.1"
edition = "2021"

[dependencies]
approx = "0.5.1"
bevy = { version = "0.7", default-features = false }
core-foundation = "0.9"
dioxus-core = { version = "0.2", features = ["serialize"] }
dioxus-hooks = "0.2"
dioxus-html = { version = "0.2", features = ["serialize"] }
dunce = "1.0"
futures-channel = "0.3.21"
futures-intrusive = "0.4"
log = "0.4"
mime_guess = "2.0"
raw-window-handle = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
tokio = { version = "1.18", features = ["rt-multi-thread"], default-features = false }
webbrowser = "0.5"
wry = "0.16"
